services:
  db:
    image: 'postgres:14-alpine'
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=alquilame
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5555:5432"

  client:
    image: 'dpage/pgadmin4'
    container_name: client
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - db
    ports:
      - "5050:80"